name: application_icon_example
description: Demonstrates how to use the application_icon plugin.
version: 1.0.0

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.26.0-17.5.pre"

dependencies:
  flutter:
    sdk: flutter

  application_icon:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true