name: application_icon
description: This package provides a widget which shows the application icon of your app.
version: 2.0.0
homepage: https://uekoetter.dev/
repository: https://github.com/ueman/application_icon
issue_tracker: https://github.com/ueman/application_icon/issues

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.26.0-17.5.pre"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.ju.application_icon
        pluginClass: ApplicationIconPlugin
      ios:
        pluginClass: ApplicationIconPlugin